# Generated by Django 4.1.2 on 2022-10-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disc',
            old_name='plasitc',
            new_name='plastic',
        ),
    ]
