# Generated by Django 4.1.2 on 2022-10-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_plasitc_disc_plastic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.CharField(max_length=3)),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.disc')),
            ],
        ),
    ]
